### ISSUE TITLE
The u8 packing doesn't work.

### ISSUE THREAD

**Issue by Peter0x44** [TheShadowEevee/Sharpii-NetCore#3] opened 2020-04-09 16:44 UTC
When trying to unpack the 00000002.app for the purpose of injecting flash games, the output seems broken. When packed into a wad, it simply gives a purple screen when installed and launched from Dolphin. I tried packing and unpacking the base wad, that was functional and worked. I then tried packing the wad with a 00000002.app produced by another tool (wszst), and that also worked. I can only conclude that the issue is with sharpii here.

**Comment by TheShadowEevee** [comment] 2020-04-09 16:49
I'm looking into it now.

**Comment by TheShadowEevee** [comment] 2020-04-09 21:33
It seems like the issue may be due to the way libWiiSharp is implemented. I am looking into a fix.

**Comment by Peter0x44** [comment] 2020-04-16 17:23
I asked a windows user to try this with the original sharpii, it failed in the same way. I think it's possible that this isn't an issue with your port, and really is to do with libWiiSharp.
I'd love if you can investigate further.

**Comment by Peter0x44** [comment] 2020-04-16 19:25
Ignore that, turns out it was a different issue (not the fault of sharpii, it works)

**Comment by TheShadowEevee** [comment] 2020-05-07 02:24
Update: After finally getting a test script for Sharpii working, I got some SHA256 hashes of various 00000002.app files shown below.

```
OG Sharpii Clean Sha256: 
94c7955ac052c23c1afcb7539f93e31c571663de1b3b54ec0dc7b0bdf5860570  
OGSharpii-Clean/00000002.app

OG Sharpii Repacked Sha256: 
6514bc757adaa15f13ebf1ca3325636cf15e83ad6f67751aaebb82fee5f4e035  
OGSharpii-Repacked/00000002.app

Sharpii Net Clean Sha256: 
94c7955ac052c23c1afcb7539f93e31c571663de1b3b54ec0dc7b0bdf5860570  
SharpiiNet-Clean/00000002.app

Sharpii Net Repacked Sha256: 
6514bc757adaa15f13ebf1ca3325636cf15e83ad6f67751aaebb82fee5f4e035  
SharpiiNet-Repacked/00000002.app
```
(Clean means not repacked)

It seems to be the underlying U8 packing that's at fault, which would be due to libWiiSharp. I would have to decipher how libWiiSharp's U8 utility's work in order to fix this issue. This will likely take quite awhile to fix if possible.

**Comment by TheShadowEevee** [comment] 2020-05-07 03:32
After some quick research I discovered that  the old libWiiSharp repo had an unfixed bug involving the U8 packing. It's likely the issue is related, and will hopefully help in solving this issue.

Link: https://github.com/dnasdw/libwiisharp/issues/3

This link leads to a Github repo exported from https://code.google.com/p/libwiisharp, the issue came from there.

**Comment by TheShadowEevee** [comment] 2020-12-28 19:03
I'm closing this issue for now, things seem to be working fine. If this problem arises again someone can reopen this with more details but for now I think it's safe to close the issue.

**Closed as completed by TheShadowEevee** 2020-12-28 19:03 UTC
Labels: bug, Testing Needed
